// AUTO-GENERATED by besa generate. DO NOT EDIT.


export type MutationFn<TInput, TOutput, TRepos extends object> = (
  input: TInput,
  repos: TRepos,
) => Promise<TOutput>;

export function defineMutation<TInput, TOutput, TRepos extends object>(
  fn: MutationFn<TInput, TOutput, TRepos>,
): MutationFn<TInput, TOutput, TRepos> {
  return fn;
}
