// AUTO-GENERATED by besa generate. DO NOT EDIT.


export type QueryFn<TInput, TOutput, TRepos extends object> = (
  input: TInput,
  repos: TRepos,
) => Promise<TOutput>;

export function defineQuery<TInput, TOutput, TRepos extends object>(
  fn: QueryFn<TInput, TOutput, TRepos>,
): QueryFn<TInput, TOutput, TRepos> {
  return fn;
}
