// AUTO-GENERATED by besa generate. DO NOT EDIT.


export interface BaseProduct {
  id: string;
  // TODO: define BaseProduct fields
}

export interface BaseProductImage {
  id: string;
  // TODO: define BaseProductImage fields
}

export interface BaseCart {
  id: string;
  // TODO: define BaseCart fields
}

export interface BaseCartProduct {
  id: string;
  // TODO: define BaseCartProduct fields
}

export interface BaseOrder {
  id: string;
  // TODO: define BaseOrder fields
}

export interface BasePurchasedProduct {
  id: string;
  // TODO: define BasePurchasedProduct fields
}

export interface BaseShipment {
  id: string;
  // TODO: define BaseShipment fields
}

export interface BaseShipmentProduct {
  id: string;
  // TODO: define BaseShipmentProduct fields
}

export interface BaseUser {
  id: string;
  // TODO: define BaseUser fields
}
