// AUTO-GENERATED by besa generate. DO NOT EDIT.


export type CatalogContextAggregates = "product";
export type CartContextAggregates = "cart";
export type OrderContextAggregates = "order";
export type ShippingContextAggregates = "shipment";
export type IdentityContextAggregates = "user";

export type ContextAggregateMap = {
  catalog: CatalogContextAggregates;
  cart: CartContextAggregates;
  order: OrderContextAggregates;
  shipping: ShippingContextAggregates;
  identity: IdentityContextAggregates;
};
