// AUTO-GENERATED by besa generate. DO NOT EDIT.


import type { OrderReadService } from "../../cross-context/order-read-service-interface";
import type { MutableShipmentRepository } from "../../repositories/shipment-repository";
import { defineMutation } from "../mutation";
import type { MutationFn } from "../mutation";

export type CreateShipmentRepos = {
  shipment: MutableShipmentRepository;
  orderReadService: OrderReadService;
};

export type CreateShipmentExecute = MutationFn<unknown, unknown, CreateShipmentRepos>;

export { defineMutation };
