// AUTO-GENERATED by besa generate. DO NOT EDIT.


import type { ReadonlyShipmentRepository } from "../../repositories/shipment-repository";
import { defineQuery } from "../query";
import type { QueryFn } from "../query";

export type GetShipmentStatusRepos = {
  shipment: ReadonlyShipmentRepository;
};

export type GetShipmentStatusExecute = QueryFn<unknown, unknown, GetShipmentStatusRepos>;

export { defineQuery };
