// AUTO-GENERATED by besa generate. DO NOT EDIT.


import type { BaseOrder } from "../types/aggregate-types";

export interface OrderReadService {
  findById(id: string): Promise<BaseOrder | null>;
}
