// AUTO-GENERATED by besa generate. DO NOT EDIT.


import type { BaseProduct } from "../types/aggregate-types";

export interface ProductReadService {
  findById(id: string): Promise<BaseProduct | null>;
}
