// AUTO-GENERATED by besa generate. DO NOT EDIT.


import type { CartReadService } from "../../cross-context/cart-read-service-interface";
import type { MutableOrderRepository } from "../../repositories/order-repository";
import { defineMutation } from "../mutation";
import type { MutationFn } from "../mutation";

export type CheckoutRepos = {
  order: MutableOrderRepository;
  cartReadService: CartReadService;
};

export type CheckoutExecute = MutationFn<unknown, unknown, CheckoutRepos>;

export { defineMutation };
