// AUTO-GENERATED by besa generate. DO NOT EDIT.


import type { ReadonlyOrderRepository } from "../../repositories/order-repository";
import { defineQuery } from "../query";
import type { QueryFn } from "../query";

export type GetPurchaseHistoryRepos = {
  order: ReadonlyOrderRepository;
};

export type GetPurchaseHistoryExecute = QueryFn<unknown, unknown, GetPurchaseHistoryRepos>;

export { defineQuery };
