// AUTO-GENERATED by besa generate. DO NOT EDIT.


import type { ProductReadService } from "../../cross-context/product-read-service-interface";
import type { MutableCartRepository } from "../../repositories/cart-repository";
import { defineMutation } from "../mutation";
import type { MutationFn } from "../mutation";

export type AddProductRepos = {
  cart: MutableCartRepository;
  productReadService: ProductReadService;
};

export type AddProductExecute = MutationFn<unknown, unknown, AddProductRepos>;

export { defineMutation };
