// AUTO-GENERATED by besa generate. DO NOT EDIT.


import type { ReadonlyCartRepository } from "../../repositories/cart-repository";
import { defineQuery } from "../query";
import type { QueryFn } from "../query";

export type GetCartRepos = {
  cart: ReadonlyCartRepository;
};

export type GetCartExecute = QueryFn<unknown, unknown, GetCartRepos>;

export { defineQuery };
