// AUTO-GENERATED by besa generate. DO NOT EDIT.


import type { ReadonlyProductRepository } from "../../repositories/product-repository";
import { defineQuery } from "../query";
import type { QueryFn } from "../query";

export type GetProductRepos = {
  product: ReadonlyProductRepository;
};

export type GetProductExecute = QueryFn<unknown, unknown, GetProductRepos>;

export { defineQuery };
