import path from "node:path";
import type { BesaConfig } from "./config.js";
import { writeFile, writeFileOnce } from "./utils/fs.js";
import {
  toPascalCase,
  toCamelCase,
  toKebabCase,
  useCaseNameToCamelCase,
} from "./utils/naming.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function autoGenHeader(): string {
  return "// AUTO-GENERATED by besa generate. DO NOT EDIT.\n";
}

function collectCrossContextVias(
  config: BesaConfig
): Map<string, { via: string; fromContext: string; toContext: string }> {
  const map = new Map<
    string,
    { via: string; fromContext: string; toContext: string }
  >();
  for (const [ctxName, ctx] of Object.entries(config.contexts)) {
    for (const ccr of ctx.cross_context_reads ?? []) {
      if (!map.has(ccr.via)) {
        map.set(ccr.via, {
          via: ccr.via,
          fromContext: ctxName,
          toContext: ccr.context,
        });
      }
    }
  }
  return map;
}

function getRootTypesForContext(
  config: BesaConfig,
  targetContextName: string
): string[] {
  const roots: string[] = [];
  for (const agg of Object.values(config.aggregates)) {
    if (agg.context === targetContextName) {
      roots.push(agg.root);
    }
  }
  return roots;
}

// ---------------------------------------------------------------------------
// Always-overwrite generators
// ---------------------------------------------------------------------------

function generateAggregateTypes(config: BesaConfig): string {
  const lines: string[] = [autoGenHeader(), ""];
  for (const agg of Object.values(config.aggregates)) {
    const names = [agg.root, ...agg.entities];
    for (const name of names) {
      lines.push(`export interface Base${name} {`);
      lines.push(`  id: string;`);
      lines.push(`  // TODO: define Base${name} fields`);
      lines.push(`}`);
      lines.push("");
    }
  }
  return lines.join("\n");
}

function generateContextScope(config: BesaConfig): string {
  const lines: string[] = [autoGenHeader(), ""];

  for (const [ctxName, ctx] of Object.entries(config.contexts)) {
    const pascal = toPascalCase(ctxName);
    const aggLiterals = ctx.aggregates.map((a) => `"${a}"`).join(" | ");
    lines.push(
      `export type ${pascal}ContextAggregates = ${aggLiterals || "never"};`
    );
  }
  lines.push("");
  lines.push("export type ContextAggregateMap = {");
  for (const [ctxName, ctx] of Object.entries(config.contexts)) {
    const pascal = toPascalCase(ctxName);
    if (ctx.aggregates.length > 0) {
      lines.push(`  ${ctxName}: ${pascal}ContextAggregates;`);
    } else {
      lines.push(`  ${ctxName}: never;`);
    }
  }
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

function generateRepository(aggName: string, rootName: string): string {
  const pascal = toPascalCase(rootName);
  const lines: string[] = [
    autoGenHeader(),
    "",
    `import type { Base${pascal} } from "../types/aggregate-types";`,
    "",
    `export interface Mutable${pascal}Repository {`,
    `  findById(id: string): Promise<Base${pascal} | null>;`,
    `  save(entity: Base${pascal}): Promise<void>;`,
    `  delete(id: string): Promise<void>;`,
    `}`,
    "",
    `export interface Readonly${pascal}Repository {`,
    `  findById(id: string): Promise<Base${pascal} | null>;`,
    `}`,
    "",
  ];
  void aggName;
  return lines.join("\n");
}

function generateMutationContract(): string {
  return [
    autoGenHeader(),
    "",
    "export type MutationFn<TInput, TOutput, TRepos extends object> = (",
    "  input: TInput,",
    "  repos: TRepos,",
    ") => Promise<TOutput>;",
    "",
    "export function defineMutation<TInput, TOutput, TRepos extends object>(",
    "  fn: MutationFn<TInput, TOutput, TRepos>,",
    "): MutationFn<TInput, TOutput, TRepos> {",
    "  return fn;",
    "}",
    "",
  ].join("\n");
}

function generateQueryContract(): string {
  return [
    autoGenHeader(),
    "",
    "export type QueryFn<TInput, TOutput, TRepos extends object> = (",
    "  input: TInput,",
    "  repos: TRepos,",
    ") => Promise<TOutput>;",
    "",
    "export function defineQuery<TInput, TOutput, TRepos extends object>(",
    "  fn: QueryFn<TInput, TOutput, TRepos>,",
    "): QueryFn<TInput, TOutput, TRepos> {",
    "  return fn;",
    "}",
    "",
  ].join("\n");
}

function generateCrossContextInterface(
  via: string,
  rootTypes: string[]
): string {
  const baseImportTypes = rootTypes.map((r) => `Base${r}`).join(", ");
  const lines: string[] = [
    autoGenHeader(),
    "",
    `import type { ${baseImportTypes} } from "../types/aggregate-types";`,
    "",
    `export interface ${via} {`,
  ];
  for (const root of rootTypes) {
    lines.push(`  findById(id: string): Promise<Base${root} | null>;`);
  }
  lines.push(`}`);
  lines.push("");
  return lines.join("\n");
}

function generateUseCaseExecuteType(
  ucPath: string,
  uc: { type: "mutation" | "query"; aggregates: string[]; cross_context_reads?: string[] | undefined },
  config: BesaConfig
): string {
  const camelName = useCaseNameToCamelCase(ucPath);
  const pascalName = toPascalCase(camelName);
  const contractFn = uc.type === "mutation" ? "defineMutation" : "defineQuery";
  const contractType = uc.type === "mutation" ? "MutationFn" : "QueryFn";

  const imports: string[] = [
    `import { ${contractFn} } from "../${uc.type === "mutation" ? "mutation" : "query"}";`,
    `import type { ${contractType} } from "../${uc.type === "mutation" ? "mutation" : "query"}";`,
  ];

  const repoEntries: string[] = [];

  for (const aggName of uc.aggregates) {
    const agg = config.aggregates[aggName];
    if (agg === undefined) continue;
    const pascal = toPascalCase(agg.root);
    const repoType = uc.type === "mutation"
      ? `Mutable${pascal}Repository`
      : `Readonly${pascal}Repository`;
    const kebab = toKebabCase(aggName);
    imports.push(`import type { ${repoType} } from "../../repositories/${kebab}-repository";`);
    repoEntries.push(`  ${aggName}: ${repoType};`);
  }

  const contextCfg = config.contexts[uc.aggregates.length > 0
    ? (config.aggregates[uc.aggregates[0]!]?.context ?? "")
    : ""];

  for (const ccrContextName of uc.cross_context_reads ?? []) {
    const ccrDecl = (contextCfg?.cross_context_reads ?? []).find(
      (c: { context: string; via: string }) => c.context === ccrContextName
    );
    if (ccrDecl === undefined) continue;
    const kebabVia = toKebabCase(ccrDecl.via);
    imports.push(`import type { ${ccrDecl.via} } from "../../cross-context/${kebabVia}-interface";`);
    repoEntries.push(`  ${toCamelCase(ccrDecl.via)}: ${ccrDecl.via};`);
  }

  const sortedImports = imports.sort((a, b) => {
    const pathA = a.match(/from "([^"]+)"/)?.[1] ?? "";
    const pathB = b.match(/from "([^"]+)"/)?.[1] ?? "";
    return pathA.localeCompare(pathB);
  });

  const repoTypeName = `${pascalName}Repos`;

  return [
    autoGenHeader(),
    "",
    ...sortedImports,
    "",
    `export type ${repoTypeName} = {`,
    ...repoEntries,
    "};",
    "",
    `export type ${pascalName}Execute = ${contractType}<unknown, unknown, ${repoTypeName}>;`,
    "",
    `export { ${contractFn} };`,
    "",
  ].join("\n");
}

function generateEslintConfig(config: BesaConfig): string {
  type BoundaryElement = { type: string; pattern: string };
  type BoundaryRule = { from: string; allow: string[] };

  const elements: BoundaryElement[] = [];
  const rules: BoundaryRule[] = [];

  for (const ctxName of Object.keys(config.contexts)) {
    elements.push({
      type: `${ctxName}-context`,
      pattern: `src/contexts/${ctxName}/**`,
    });
  }
  elements.push({ type: "infra", pattern: "src/infra/**" });
  elements.push({ type: "besa-generated", pattern: "src/besa-generated/**" });
  elements.push({ type: "shared", pattern: "src/_shared/**" });

  for (const ctxName of Object.keys(config.contexts)) {
    rules.push({
      from: `${ctxName}-context`,
      allow: ["besa-generated", "shared"],
    });
  }
  rules.push({ from: "infra", allow: ["besa-generated"] });
  rules.push({ from: "besa-generated", allow: [] });
  rules.push({ from: "shared", allow: [] });

  const eslintConfig = {
    $schema: "https://json.schemastore.org/eslintrc",
    plugins: ["boundaries"],
    settings: {
      "boundaries/elements": elements,
    },
    rules: {
      "boundaries/element-types": [
        "error",
        { default: "disallow", rules },
      ],
      "@typescript-eslint/no-explicit-any": "error",
    },
  };

  return JSON.stringify(eslintConfig, null, 2) + "\n";
}

// ---------------------------------------------------------------------------
// Scaffold generators (writeFileOnce — user edits these)
// ---------------------------------------------------------------------------

function generateDomainScaffold(aggName: string, rootName: string, contextName: string): string {
  const pascal = toPascalCase(rootName);
  void aggName; void contextName;
  return [
    `import type { Base${pascal} } from "../../../besa-generated/types/aggregate-types";`,
    "",
    `// Domain functions for ${pascal}`,
    `// Add business logic here. These functions must not depend on infra/.`,
    "",
    `export function create${pascal}(id: string): Base${pascal} {`,
    `  return { id };`,
    `}`,
    "",
  ].join("\n");
}

function generateExecuteScaffold(
  ucPath: string,
  uc: { type: "mutation" | "query"; aggregates: string[]; cross_context_reads?: string[] | undefined },
  config: BesaConfig
): string {
  const camelName = useCaseNameToCamelCase(ucPath);
  const pascalName = toPascalCase(camelName);
  const idx = ucPath.indexOf("/");
  const useCaseName = idx === -1 ? ucPath : ucPath.slice(idx + 1);
  const contractFn = uc.type === "mutation" ? "defineMutation" : "defineQuery";

  const contextCfg = config.contexts[uc.aggregates.length > 0
    ? (config.aggregates[uc.aggregates[0]!]?.context ?? "")
    : ""];

  const repoParams: string[] = [];
  for (const aggName of uc.aggregates) {
    const agg = config.aggregates[aggName];
    if (agg === undefined) continue;
    const pascal = toPascalCase(agg.root);
    const repoType = uc.type === "mutation"
      ? `Mutable${pascal}Repository`
      : `Readonly${pascal}Repository`;
    repoParams.push(`    ${aggName}: _${aggName},`);
    void repoType;
  }
  for (const ccrCtx of uc.cross_context_reads ?? []) {
    const ccrDecl = (contextCfg?.cross_context_reads ?? []).find(
      (c: { context: string; via: string }) => c.context === ccrCtx
    );
    if (ccrDecl === undefined) continue;
    repoParams.push(`    ${toCamelCase(ccrDecl.via)}: _${toCamelCase(ccrDecl.via)},`);
  }

  return [
    `import { ${contractFn} } from "../../../../besa-generated/contracts/${contractFn === "defineMutation" ? "mutation" : "query"}";`,
    `import type { ${pascalName}Repos } from "../../../../besa-generated/contracts/${uc.aggregates.length > 0 ? (config.aggregates[uc.aggregates[0]!]?.context ?? "") + "/" : ""}${useCaseName}";`,
    "",
    `export const execute = ${contractFn}<unknown, unknown, ${pascalName}Repos>(`,
    `  async (_input, {`,
    ...repoParams,
    `  }) => {`,
    `    // TODO: implement ${ucPath}`,
    `    throw new Error("Not implemented");`,
    `  },`,
    `);`,
    "",
  ].join("\n");
}

function generateHandlerScaffold(
  ucPath: string,
  uc: { type: "mutation" | "query"; aggregates: string[]; cross_context_reads?: string[] | undefined },
  config: BesaConfig
): string {
  const idx = ucPath.indexOf("/");
  const useCaseName = idx === -1 ? ucPath : ucPath.slice(idx + 1);
  const contextName = idx === -1 ? ucPath : ucPath.slice(0, idx);
  const camelName = useCaseNameToCamelCase(ucPath);
  const pascalName = toPascalCase(camelName);
  const reposTypeName = `${pascalName}Repos`;

  const repoInjects: string[] = [];
  for (const aggName of uc.aggregates) {
    const agg = config.aggregates[aggName];
    if (agg === undefined) continue;
    const pascal = toPascalCase(agg.root);
    const kebab = toKebabCase(aggName);
    const repoClass = uc.type === "mutation"
      ? `Prisma${pascal}Repository`
      : `ReadonlyPrisma${pascal}Repository`;
    repoInjects.push(`    // TODO: replace with real implementation`);
    repoInjects.push(`    // import { ${repoClass} } from "../../../../infra/${kebab}-prisma-repository";`);
    repoInjects.push(`    ${aggName}: null as never, // new ${repoClass}()`);
  }

  const contextCfg = config.contexts[contextName];
  for (const ccrCtx of uc.cross_context_reads ?? []) {
    const ccrDecl = (contextCfg?.cross_context_reads ?? []).find(
      (c: { context: string; via: string }) => c.context === ccrCtx
    );
    if (ccrDecl === undefined) continue;
    const camelVia = toCamelCase(ccrDecl.via);
    repoInjects.push(`    ${camelVia}: null as never, // inject ${ccrDecl.via} implementation`);
  }

  const contractPath = `../../../../besa-generated/contracts/${contextName}/${useCaseName}`;

  return [
    `import { execute } from "./execute";`,
    `import type { ${reposTypeName} } from "${contractPath}";`,
    "",
    `// HTTP handler for ${ucPath}`,
    `// Replace 'null as never' with real repository implementations from src/infra/.`,
    `export async function handler(input: unknown): Promise<unknown> {`,
    `  const repos: ${reposTypeName} = {`,
    ...repoInjects,
    `  };`,
    `  return execute(input, repos);`,
    `}`,
    "",
  ].join("\n");
}

function generateTestScaffold(ucPath: string, uc: { type: "mutation" | "query" }): string {
  void uc;
  return [
    `import { describe, it, expect } from "vitest";`,
    `import { execute } from "./execute";`,
    "",
    `describe("${ucPath}", () => {`,
    `  it("should throw 'Not implemented' until logic is added", async () => {`,
    `    const repos = {} as Parameters<typeof execute>[1];`,
    `    await expect(execute({}, repos)).rejects.toThrow("Not implemented");`,
    `  });`,
    `});`,
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Main generate runner
// ---------------------------------------------------------------------------

export async function runGenerate(
  cwd: string,
  config: BesaConfig,
  options: { dryRun?: boolean } = {}
): Promise<void> {
  const dry = options.dryRun ?? false;
  const genBase = path.join(cwd, "src", "besa-generated");

  // 1. aggregate-types.ts
  await writeFile(path.join(genBase, "types", "aggregate-types.ts"), generateAggregateTypes(config), dry);

  // 2. context-scope.ts
  await writeFile(path.join(genBase, "types", "context-scope.ts"), generateContextScope(config), dry);

  // 3. repositories/{aggregate}-repository.ts
  for (const [aggName, agg] of Object.entries(config.aggregates)) {
    await writeFile(
      path.join(genBase, "repositories", `${toKebabCase(aggName)}-repository.ts`),
      generateRepository(aggName, agg.root),
      dry
    );
  }

  // 4. contracts/mutation.ts + contracts/query.ts
  await writeFile(path.join(genBase, "contracts", "mutation.ts"), generateMutationContract(), dry);
  await writeFile(path.join(genBase, "contracts", "query.ts"), generateQueryContract(), dry);

  // 5. cross-context interfaces
  const vias = collectCrossContextVias(config);
  for (const [via, { toContext }] of vias) {
    const roots = getRootTypesForContext(config, toContext);
    await writeFile(
      path.join(genBase, "cross-context", `${toKebabCase(via)}-interface.ts`),
      generateCrossContextInterface(via, roots),
      dry
    );
  }

  // 6. contracts/{context}/{use-case}.ts
  for (const [ucPath, uc] of Object.entries(config["use-cases"])) {
    const idx = ucPath.indexOf("/");
    const contextName = idx === -1 ? ucPath : ucPath.slice(0, idx);
    const useCaseName = idx === -1 ? ucPath : ucPath.slice(idx + 1);
    await writeFile(
      path.join(genBase, "contracts", contextName, `${useCaseName}.ts`),
      generateUseCaseExecuteType(ucPath, uc, config),
      dry
    );
  }

  // 7. .eslintrc-besa.json
  await writeFile(path.join(cwd, ".eslintrc-besa.json"), generateEslintConfig(config), dry);

  // 8. Scaffold files (writeFileOnce — user edits these)
  for (const [aggName, agg] of Object.entries(config.aggregates)) {
    await writeFileOnce(
      path.join(cwd, "src", "contexts", agg.context, "domain", `${toKebabCase(aggName)}.ts`),
      generateDomainScaffold(aggName, agg.root, agg.context),
      dry
    );
  }

  for (const [ucPath, uc] of Object.entries(config["use-cases"])) {
    const idx = ucPath.indexOf("/");
    const contextName = idx === -1 ? ucPath : ucPath.slice(0, idx);
    const useCaseName = idx === -1 ? ucPath : ucPath.slice(idx + 1);
    const ucDir = path.join(cwd, "src", "contexts", contextName, "use-cases", useCaseName);

    await writeFileOnce(path.join(ucDir, "execute.ts"), generateExecuteScaffold(ucPath, uc, config), dry);
    await writeFileOnce(path.join(ucDir, "handler.ts"), generateHandlerScaffold(ucPath, uc, config), dry);
    await writeFileOnce(path.join(ucDir, "execute.test.ts"), generateTestScaffold(ucPath, uc), dry);
  }
}
