// AUTO-GENERATED by besa generate. DO NOT EDIT.


import type { BaseCart } from "../types/aggregate-types";

export interface MutableCartRepository {
  findById(id: string): Promise<BaseCart | null>;
  save(entity: BaseCart): Promise<void>;
  delete(id: string): Promise<void>;
}

export interface ReadonlyCartRepository {
  findById(id: string): Promise<BaseCart | null>;
}
