// AUTO-GENERATED by besa generate. DO NOT EDIT.


import type { BaseOrder } from "../types/aggregate-types";

export interface MutableOrderRepository {
  findById(id: string): Promise<BaseOrder | null>;
  save(entity: BaseOrder): Promise<void>;
  delete(id: string): Promise<void>;
}

export interface ReadonlyOrderRepository {
  findById(id: string): Promise<BaseOrder | null>;
}
