// AUTO-GENERATED by besa generate. DO NOT EDIT.


import type { BaseProduct } from "../types/aggregate-types";

export interface MutableProductRepository {
  findById(id: string): Promise<BaseProduct | null>;
  save(entity: BaseProduct): Promise<void>;
  delete(id: string): Promise<void>;
}

export interface ReadonlyProductRepository {
  findById(id: string): Promise<BaseProduct | null>;
}
