// AUTO-GENERATED by besa generate. DO NOT EDIT.


import type { BaseShipment } from "../types/aggregate-types";

export interface MutableShipmentRepository {
  findById(id: string): Promise<BaseShipment | null>;
  save(entity: BaseShipment): Promise<void>;
  delete(id: string): Promise<void>;
}

export interface ReadonlyShipmentRepository {
  findById(id: string): Promise<BaseShipment | null>;
}
