// AUTO-GENERATED by besa generate. DO NOT EDIT.


import type { BaseUser } from "../types/aggregate-types";

export interface MutableUserRepository {
  findById(id: string): Promise<BaseUser | null>;
  save(entity: BaseUser): Promise<void>;
  delete(id: string): Promise<void>;
}

export interface ReadonlyUserRepository {
  findById(id: string): Promise<BaseUser | null>;
}
